### ISSUE TITLE
Potential solution to full in-memory startup

### ISSUE THREAD

**Issue by vakabus** [exyi/anyexec2C#8]
`memfd_create` syscall creates an anonymous file stored in RAM. `fexecve` syscall can execute a file descriptor or we could execute the `/proc/self/fd/FD_NUMBER` symbolic file by a normal exec. This could make startup time considerably shorter.

**Comment by exyi** [comment]
Nice! This would also remove the clutter we create in the working directory and remove the need for write rights on disk :)
